[package]
name = "wag"
version = "0.1.0"
edition = "2021"

[dependencies]
async_object = { path = "../async_object" }
async_object_derive = { path = "../async_object/async_object_derive" }
futures = "0.3.17"
thiserror = "1.0"
float-ord = "0.3.2"
winit = "0.26.0"

[dependencies.windows]
version = "0.29.0"
features = [
    "std",
    "Foundation_Collections",
    "Foundation_Numerics",
    "Graphics",
    "System",
    "UI_Composition_Desktop",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_WinRT",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_WinRT_Composition",
]
